package entite;
// Generated May 14, 2020 12:05:01 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Question generated by hbm2java
 */
public class Question  implements java.io.Serializable {


     private long idQuestion;
     private String enonceQuestion;
     private Set reponsePossibles = new HashSet(0);
     private Set reponsePossibles_1 = new HashSet(0);

    public Question() {
    }

	
    public Question(long idQuestion) {
        this.idQuestion = idQuestion;
    }
    public Question(long idQuestion, String enonceQuestion, Set reponsePossibles, Set reponsePossibles_1) {
       this.idQuestion = idQuestion;
       this.enonceQuestion = enonceQuestion;
       this.reponsePossibles = reponsePossibles;
       this.reponsePossibles_1 = reponsePossibles_1;
    }
   
    public long getIdQuestion() {
        return this.idQuestion;
    }
    
    public void setIdQuestion(long idQuestion) {
        this.idQuestion = idQuestion;
    }
    public String getEnonceQuestion() {
        return this.enonceQuestion;
    }
    
    public void setEnonceQuestion(String enonceQuestion) {
        this.enonceQuestion = enonceQuestion;
    }
    public Set getReponsePossibles() {
        return this.reponsePossibles;
    }
    
    public void setReponsePossibles(Set reponsePossibles) {
        this.reponsePossibles = reponsePossibles;
    }
    public Set getReponsePossibles_1() {
        return this.reponsePossibles_1;
    }
    
    public void setReponsePossibles_1(Set reponsePossibles_1) {
        this.reponsePossibles_1 = reponsePossibles_1;
    }




}


