package entite;
// Generated May 14, 2020 12:05:01 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ReponsePossible generated by hbm2java
 */
public class ReponsePossible  implements java.io.Serializable {


     private long idReponse;
     private Question question;
     private String enonceReponse;
     private Set questions = new HashSet(0);

    public ReponsePossible() {
    }

	
    public ReponsePossible(long idReponse) {
        this.idReponse = idReponse;
    }
    public ReponsePossible(long idReponse, Question question, String enonceReponse, Set questions) {
       this.idReponse = idReponse;
       this.question = question;
       this.enonceReponse = enonceReponse;
       this.questions = questions;
    }
   
      public ReponsePossible(long idReponse, Question question, String enonceReponse) {
       this.idReponse = idReponse;
       this.question = question;
       this.enonceReponse = enonceReponse;
       
    }
    public long getIdReponse() {
        return this.idReponse;
    }
    
    public void setIdReponse(long idReponse) {
        this.idReponse = idReponse;
    }
    public Question getQuestion() {
        return this.question;
    }
    
    public void setQuestion(Question question) {
        this.question = question;
    }
    public String getEnonceReponse() {
        return this.enonceReponse;
    }
    
    public void setEnonceReponse(String enonceReponse) {
        this.enonceReponse = enonceReponse;
    }
    public Set getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Set questions) {
        this.questions = questions;
    }




}

