package entite;
// Generated May 14, 2020 12:05:01 AM by Hibernate Tools 4.3.1



/**
 * ScoreId generated by hbm2java
 */
public class ScoreId  implements java.io.Serializable {


     private short score;
     private String utilisateurName;

    public ScoreId() {
    }

    public ScoreId(short score, String utilisateurName) {
       this.score = score;
       this.utilisateurName = utilisateurName;
    }


   
    public short getScore() {
        return this.score;
    }
    
    public void setScore(short score) {
        this.score = score;
    }
    public String getUtilisateurName() {
        return this.utilisateurName;
    }
    
    public void setUtilisateurName(String utilisateurName) {
        this.utilisateurName = utilisateurName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ScoreId) ) return false;
		 ScoreId castOther = ( ScoreId ) other; 
         
		 return (this.getScore()==castOther.getScore())
 && ( (this.getUtilisateurName()==castOther.getUtilisateurName()) || ( this.getUtilisateurName()!=null && castOther.getUtilisateurName()!=null && this.getUtilisateurName().equals(castOther.getUtilisateurName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getScore();
         result = 37 * result + ( getUtilisateurName() == null ? 0 : this.getUtilisateurName().hashCode() );
         return result;
   }   


}


