package entite;
// Generated May 14, 2020 12:05:01 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Utilisateur generated by hbm2java
 */
public class Utilisateur  implements java.io.Serializable {


     private String utilisateurName;
     private String motdepass;
     private String typeuser;
     private Set scores = new HashSet(0);

    public Utilisateur() {
    }
    
    public Utilisateur(String utilisateurName) {
        this.utilisateurName = utilisateurName;
    }

	
    public Utilisateur(String utilisateurName, String motdepass, String typeuser) {
        this.utilisateurName = utilisateurName;
        this.motdepass = motdepass;
        this.typeuser = typeuser;
    }
    public Utilisateur(String utilisateurName, String motdepass, String typeuser, Set scores) {
       this.utilisateurName = utilisateurName;
       this.motdepass = motdepass;
       this.typeuser = typeuser;
       this.scores = scores;
    }
   
    public String getUtilisateurName() {
        return this.utilisateurName;
    }
    
    public void setUtilisateurName(String utilisateurName) {
        this.utilisateurName = utilisateurName;
    }
    public String getMotdepass() {
        return this.motdepass;
    }
    
    public void setMotdepass(String motdepass) {
        this.motdepass = motdepass;
    }
    public String getTypeuser() {
        return this.typeuser;
    }
    
    public void setTypeuser(String typeuser) {
        this.typeuser = typeuser;
    }
    public Set getScores() {
        return this.scores;
    }
    
    public void setScores(Set scores) {
        this.scores = scores;
    }




}


